POST http://localhost:9000/http/users/
Content-Type: application/json

{
  "name": "Admin11",
  "email": "Admin@isel.ipl.pt11",
  "password": "123411"
}

###
PUT http://localhost:9000/http/users/auth
Content-Type: application/json

{
  "email": "aaa@g",
  "password": "111"
}

###
GET http://localhost:9000/http/users/me
Content-Type: application/json
Authorization: f725b616-7545-4761-af61-22c3b1edf242


###
GET http://localhost:9000/http/users/
Content-Type: application/json

{
"name": "Admin11",
"email": "Admin@isel.ipl.pt11",
"password": "123411"
}

###
GET http://localhost:9000/http/users/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJBTkRSRU5VTkVTQVBJIiwidXNlckVtYWlsIjoiQWRtaW5AaXNlbC5pcGwucHQxMSIsImV4cCI6MTc1NDUyMjY0MX0.YpFh9aH7X5XQZkhAlJMbaSqLGF6VbMUjsdQDZ_9mbaw

###
GET http://localhost:9000/http/games/
Content-Type: application/json
